% plot WRR photodiode's output voltage for all cases of US3: 
% with perma-proto board and PCB 2.1. 
% Only iPhone (no Multimeter) data
% No data for "no filter" anymore b/c of amplifier. Min G > 2, so 
% would saturate.
% The five pot positions are: max CCW, 12:00, 3:00, 6:00, max CW
% for 20220329 SR
close all;

blue =    [0.0000, 0.4470, 0.7410];
rust =    [0.8500, 0.3250, 0.0980];
gold =    [0.9290, 0.6940, 0.1250];
purple =  [0.4940, 0.1840, 0.5560];
green =   [0.4660, 0.6740, 0.1880];
ciel =    [0.3010, 0.7450, 0.9330];
cherry =  [0.6350, 0.0780, 0.1840];
red =     [1.0, 0.0, 0.0];
black =   [0.0, 0.0, 0.0];
magenta = [1.0, 0.0, 1.0];
myTextFont = 20;

% 3/25 dataset: perma-proto board 850nm BP,4 pot positions,no MBA
data0Vin  = [ 205, 213, 207, 228 ];
data0Vout = [ 405, 450, 648, 718];
data0Vpot = [ 205, 209, 209, 230];

% 3/25 dataset: perma-proto board 890nm BP,4 pot positions,no MBA
data1Vin  = [ 47, 46, 44, 46 ];
data1Vout = [ 89, 99, 134, 489];
data1Vpot = [ 45, 46, 44, 43];

% 3/25 dataset: perma-proto board 900nm BP,4 pot positions,no MBA
data2Vin  = [ 2, 8, 7, 4];
data2Vout = [ 4, 7, 9, 24];
data2Vpot = [ 2, 2, 4, 2];

% 3/25 dataset: perma-proto board 850nm BP,4 pot positions, with MBA
data3Vin  = [ 389, 392, 375, 373];
data3Vout = [ 768, 851, 1157, 1164 ];
data3Vpot = [ 384, 392, 375, 212];

% 3/25 dataset: perma-proto board 890nm BP,4 pot positions, with MBA
data4Vin  = [ 56, 57, 57, 59];
data4Vout = [ 115, 128, 182, 220];
data4Vpot = [ 55, 59, 57, 60];

% 3/25 dataset: perma-proto board 900nm BP,4 pot positions, with MBA
data5Vin  = [ 13, 11, 10, 12];
data5Vout = [ 16, 15, 18, 38];
data5Vpot = [ 13, 11, 14, 12 ];
% --------------------------------------------------------------
% 3/28 dataset: PCB v2.1 board 850nm BP,4 pot positions,no MBA
data6Vin  = [ 64, 63, 59, 56];
data6Vout = [ 129, 134, 193, 404];
data6Vpot = [ 68, 66, 63, 60 ];

% 3/28 dataset: PCB v2.1 board 890nm BP,4 pot positions,no MBA
data7Vin  = [ 187, 176, 170, 172 ];
data7Vout = [ 358, 383, 540, 1210];
data7Vpot = [ 182, 175, 173, 171];

% 3/28 dataset: PCB v2.1 board 900nm BP,4 pot positions,no MBA
data8Vin  = [ 9, 8, 7, 10 ];
data8Vout = [ 13, 13, 16, 35 ];
data8Vpot = [ 8, 10, 8, 6];

% 3/28 dataset: PCB v2.1 board 850nm BP,4 pot positions, with MBA
data9Vin  = [ 94, 110, 200, 112];
data9Vout = [ 190, 241, 621, 958];
data9Vpot = [ 93, 113, 204, 116];

% 3/28 dataset: PCB v2.1 board 890nm BP,4 pot positions, with MBA
data10Vin  = [ 93, 114, 135, 142];
data10Vout = [ 188, 246, 465, 1123];
data10Vpot = [ 93, 114, 137, 143];

% 3/28 dataset: PCB v2.1 board 900nm BP,4 pot positions, with MBA
data11Vin  = [ 5, 7, 6, 6];
data11Vout = [ 11, 13, 10, 26];
data11Vpot = [ 5, 5, 4, 9];
% --------------------------------------------------------------
% 4/3 dataset: redo 3/28 dataset
% 4/3 dataset: PCB v2.1 board 850nm BP,5 pot positions,no MBA
data12Vin  = [ 56, 67, 68, 58];
data12Vout = [ 126, 155, 212, 515 ];
data12Vpot = [ 64, 65, 63, 64];

% 4/3 dataset: PCB v2.1 board 890nm BP,5 pot positions,no MBA
data13Vin  = [ 106, 140, 136, 126];
data13Vout = [ 204, 292, 42, 971 ];
data13Vpot = [ 108, 142, 138, 121 ];

% 4/3 dataset: PCB v2.1 board 900nm BP,5 pot positions,no MBA
data14Vin  = [ 8, 8, 9, 6];
data14Vout = [ 13, 13, 19, 39 ];
data14Vpot = [ 9, 8, 9, 10];

% 4/3 dataset: PCB v2.1 board 850nm BP,5 pot positions, with MBA
data15Vin  = [ 212, 209, 226, 226];
data15Vout = [ 428, 445, 691, 1536];
data15Vpot = [ 214, 210, 226, 225, 5];

% 4/3 dataset: PCB v2.1 board 890nm BP,5 pot positions, with MBA
data16Vin  = [ 294, 465, 524, 486];
data16Vout = [ 582, 1009, 1689, 2015];
data16Vpot = [ 292, 474, 524, 281];

% 4/3 dataset: PCB v2.1 board 900nm BP,5 pot positions, with MBA
data17Vin  = [ 9, 9, 11, 10];
data17Vout = [ 18, 18, 25, 67];
data17Vpot = [ 7, 10, 14, 13];

figure
% perma proto (not done yet for PCB)
x = 1:1:4;
plot(x, data0Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',red,...
    'MarkerFaceColor',[1 .6 .6]);
hold on
plot(x, data0Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',red,...
    'MarkerFaceColor',[1 .6 .6]);
hold on
plot(x, data1Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',green,...
    'MarkerFaceColor',[.6 1 .6]);
hold on
plot(x, data1Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',green,...
    'MarkerFaceColor',[.6 1 .6]);
hold on
plot(x, data2Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',blue,...
    'MarkerFaceColor',[.6 .6 1]);
hold on
plot(x, data2Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',blue,...
    'MarkerFaceColor',[.6 .6 1]);
hold on
plot(x, data3Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',purple,...
    'MarkerFaceColor',magenta);
hold on
plot(x, data3Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',purple,...
    'MarkerFaceColor',magenta);
hold on
plot(x, data4Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',ciel,...
    'MarkerFaceColor',green);
hold on
plot(x, data4Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',ciel,...
    'MarkerFaceColor',green);
hold on
plot(x, data5Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',gold,...
    'MarkerFaceColor',blue);
hold on
plot(x, data5Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',gold,...
    'MarkerFaceColor',blue);
hold on

set(gca,'FontSize', myTextFont); % has no effect on tick label size
set(gca,'Xtick',1:1:4)
set(gca,'XtickLabel',x(1:1:4))
title('Vin and Vout using u-shaped config #3 and perma-proto board');
xlabel('Potentiometer positon adjusts gain (from ~2 to ~6.5)'); % x-axis label
ylabel('Voltage (mV)'); % y-axis label
lgd = legend('Vin 850BP -MBA','Vout 850BP -MBA','Vin 890BP -MBA',...
    'Vout 890BP -MBA','Vin 900BP -MBA','Vout 900BP -MBA',...
    'Vin 850BP +MBA','Vout 850BP +MBA','Vin 890BP +MBA',...
    'Vout 890BP +MBA','Vin 900BP +MBA','Vout 900BP +MBA',...
    'Location','northwest');
title(lgd,'Offset')

% PCB
figure

x = 1:1:4;
plot(x, data6Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',red,...
    'MarkerFaceColor',[1 .6 .6]);
hold on
plot(x, data6Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',red,...
    'MarkerFaceColor',[1 .6 .6]);
hold on
plot(x, data7Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',green,...
    'MarkerFaceColor',[.6 1 .6]);
hold on
plot(x, data7Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',green,...
    'MarkerFaceColor',[.6 1 .6]);
hold on
plot(x, data8Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',blue,...
    'MarkerFaceColor',[.6 .6 1]);
hold on
plot(x, data8Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',blue,...
    'MarkerFaceColor',[.6 .6 1]);
hold on
plot(x, data9Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',purple,...
    'MarkerFaceColor',magenta);
hold on
plot(x, data9Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',purple,...
    'MarkerFaceColor',magenta);
hold on
plot(x, data10Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',ciel,...
    'MarkerFaceColor',green);
hold on
plot(x, data10Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',ciel,...
    'MarkerFaceColor',green);
hold on
plot(x, data11Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',gold,...
    'MarkerFaceColor',blue);
hold on
plot(x, data11Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',gold,...
    'MarkerFaceColor',blue);
hold on

set(gca,'FontSize', myTextFont); % has no effect on tick label size
set(gca,'Xtick',1:1:4)
set(gca,'XtickLabel',x(1:1:4))
title('Vin and Vout using u-shaped config #3 and PCB v2.1');
xlabel('Potentiometer positon adjusts gain (from ~2 to ~6.5)'); % x-axis label
ylabel('Voltage (mV)'); % y-axis label
lgd = legend('Vin 850BP -MBA','Vout 850BP -MBA','Vin 890BP -MBA',...
    'Vout 890BP -MBA','Vin 900BP -MBA','Vout 900BP -MBA',...
    'Vin 850BP +MBA','Vout 850BP +MBA','Vin 890BP +MBA',...
    'Vout 890BP +MBA','Vin 900BP +MBA','Vout 900BP +MBA',...
    'Location','northwest');
title(lgd,'Offset')

% % Normalize by initial value
% figure
% % perma proto (not done yet for PCB)
% x = 1:1:4;
% plot(x, data0Vin/data0Vin(1),'-o','MarkerSize',10,...
%     'MarkerEdgeColor',red,...
%     'MarkerFaceColor',[1 .6 .6]);
% hold on
% plot(x, data0Vout/data0Vout(1),'-s','MarkerSize',10,...
%     'MarkerEdgeColor',red,...
%     'MarkerFaceColor',[1 .6 .6]);
% hold on
% plot(x, data1Vin/data1Vin(1),'-o','MarkerSize',10,...
%     'MarkerEdgeColor',green,...
%     'MarkerFaceColor',[.6 1 .6]);
% hold on
% plot(x, data1Vout/data1Vout(1),'-s','MarkerSize',10,...
%     'MarkerEdgeColor',green,...
%     'MarkerFaceColor',[.6 1 .6]);
% hold on
% plot(x, data2Vin/data2Vin(1),'-o','MarkerSize',10,...
%     'MarkerEdgeColor',blue,...
%     'MarkerFaceColor',[.6 .6 1]);
% hold on
% plot(x, data2Vout/data2Vout(1),'-s','MarkerSize',10,...
%     'MarkerEdgeColor',blue,...
%     'MarkerFaceColor',[.6 .6 1]);
% hold on
% plot(x, data3Vin/data3Vin(1),'-o','MarkerSize',10,...
%     'MarkerEdgeColor',purple,...
%     'MarkerFaceColor',magenta);
% hold on
% plot(x, data3Vout/data3Vout(1),'-s','MarkerSize',10,...
%     'MarkerEdgeColor',purple,...
%     'MarkerFaceColor',magenta);
% hold on
% plot(x, data4Vin/data4Vin(1),'-o','MarkerSize',10,...
%     'MarkerEdgeColor',ciel,...
%     'MarkerFaceColor',green);
% hold on
% plot(x, data4Vout/data4Vout(1),'-s','MarkerSize',10,...
%     'MarkerEdgeColor',ciel,...
%     'MarkerFaceColor',green);
% hold on
% plot(x, data5Vin/data5Vin(1),'-o','MarkerSize',10,...
%     'MarkerEdgeColor',gold,...
%     'MarkerFaceColor',blue);
% hold on
% plot(x, data5Vout/data5Vout(1),'-s','MarkerSize',10,...
%     'MarkerEdgeColor',gold,...
%     'MarkerFaceColor',blue);
% hold on
% 
% set(gca,'FontSize', myTextFont); % has no effect on tick label size
% set(gca,'Xtick',1:1:4)
% set(gca,'XtickLabel',x(1:1:4))
% title('Normalized Vin and Vout using u-shaped config #3 and perma-proto board');
% xlabel('Potentiometer positon adjusts gain (from ~2 to ~6.5)'); % x-axis label
% ylabel('Voltage (mV)'); % y-axis label
% lgd = legend('Vin 850BP -MBA','Vout 850BP -MBA','Vin 890BP -MBA',...
%     'Vout 890BP -MBA','Vin 900BP -MBA','Vout 900BP -MBA',...
%     'Vin 850BP +MBA','Vout 850BP +MBA','Vin 890BP +MBA',...
%     'Vout 890BP +MBA','Vin 900BP +MBA','Vout 900BP +MBA',...
%     'Location','northwest');
% title(lgd,'Offset')
% 
% % Normalize by initial value and subtract background
% figure
% % perma proto (not done yet for PCB)
% x = 1:1:4;
% plot(x, data6Vin/data6Vin(1) - data0Vin/data0Vin(1),'-o','MarkerSize',10,...
%     'MarkerEdgeColor',red,...
%     'MarkerFaceColor',[1 .6 .6]);
% hold on
% plot(x, data6Vout/data6Vout(1) - data0Vout/data0Vout(1),'-s','MarkerSize',10,...
%     'MarkerEdgeColor',red,...
%     'MarkerFaceColor',[1 .6 .6]);
% hold on
% plot(x, data7Vin/data7Vin(1) - data1Vin/data1Vin(1),'-o','MarkerSize',10,...
%     'MarkerEdgeColor',green,...
%     'MarkerFaceColor',[.6 1 .6]);
% hold on
% plot(x, data7Vout/data7Vout(1) - data1Vout/data1Vout(1),'-s','MarkerSize',10,...
%     'MarkerEdgeColor',green,...
%     'MarkerFaceColor',[.6 1 .6]);
% hold on
% plot(x, data8Vin/data8Vin(1) - data2Vin/data2Vin(1),'-o','MarkerSize',10,...
%     'MarkerEdgeColor',blue,...
%     'MarkerFaceColor',[.6 .6 1]);
% hold on
% plot(x, data8Vout/data8Vout(1) - data2Vout/data2Vout(1),'-s','MarkerSize',10,...
%     'MarkerEdgeColor',blue,...
%     'MarkerFaceColor',[.6 .6 1]);
% hold on
% plot(x, data9Vin/data9Vin(1) - data3Vin/data3Vin(1),'-o','MarkerSize',10,...
%     'MarkerEdgeColor',purple,...
%     'MarkerFaceColor',magenta);
% hold on
% plot(x, data9Vout/data9Vout(1) - data3Vout/data3Vout(1),'-s','MarkerSize',10,...
%     'MarkerEdgeColor',purple,...
%     'MarkerFaceColor',magenta);
% hold on
% plot(x, data10Vin/data10Vin(1) - data4Vin/data4Vin(1),'-o','MarkerSize',10,...
%     'MarkerEdgeColor',ciel,...
%     'MarkerFaceColor',green);
% hold on
% plot(x, data10Vout/data10Vout(1) - data4Vout/data4Vout(1),'-s','MarkerSize',10,...
%     'MarkerEdgeColor',ciel,...
%     'MarkerFaceColor',green);
% hold on
% plot(x, data11Vin/data11Vin(1) - data5Vin/data5Vin(1),'-o','MarkerSize',10,...
%     'MarkerEdgeColor',gold,...
%     'MarkerFaceColor',blue);
% hold on
% plot(x, data11Vout/data11Vout(1) - data5Vout/data5Vout(1),'-s','MarkerSize',10,...
%     'MarkerEdgeColor',gold,...
%     'MarkerFaceColor',blue);
% hold on
% 
% set(gca,'FontSize', myTextFont); % has no effect on tick label size
% set(gca,'Xtick',1:1:4)
% set(gca,'XtickLabel',x(1:1:4))
% title('Background subtracted, Normalized Vin and Vout using u-shaped config #3 and perma-proto board');
% xlabel('Potentiometer positon adjusts gain (from ~2 to ~6.5)'); % x-axis label
% ylabel('Voltage (mV)'); % y-axis label
% lgd = legend('Vin 850BP -MBA','Vout 850BP -MBA','Vin 890BP -MBA',...
%     'Vout 890BP -MBA','Vin 900BP -MBA','Vout 900BP -MBA',...
%     'Vin 850BP +MBA','Vout 850BP +MBA','Vin 890BP +MBA',...
%     'Vout 890BP +MBA','Vin 900BP +MBA','Vout 900BP +MBA',...
%     'Location','northwest');
% title(lgd,'Offset')

% PCB redo 4/3/2022
figure

x = 1:1:4;
plot(x, data12Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',red,...
    'MarkerFaceColor',[1 .6 .6]);
hold on
plot(x, data12Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',red,...
    'MarkerFaceColor',[1 .6 .6]);
hold on
plot(x, data13Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',green,...
    'MarkerFaceColor',[.6 1 .6]);
hold on
plot(x, data13Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',green,...
    'MarkerFaceColor',[.6 1 .6]);
hold on
plot(x, data14Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',blue,...
    'MarkerFaceColor',[.6 .6 1]);
hold on
plot(x, data14Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',blue,...
    'MarkerFaceColor',[.6 .6 1]);
hold on
plot(x, data15Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',purple,...
    'MarkerFaceColor',magenta);
hold on
plot(x, data15Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',purple,...
    'MarkerFaceColor',magenta);
hold on
plot(x, data16Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',ciel,...
    'MarkerFaceColor',green);
hold on
plot(x, data16Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',ciel,...
    'MarkerFaceColor',green);
hold on
plot(x, data17Vin,'-o','MarkerSize',10,...
    'MarkerEdgeColor',gold,...
    'MarkerFaceColor',blue);
hold on
plot(x, data17Vout,'-s','MarkerSize',10,...
    'MarkerEdgeColor',gold,...
    'MarkerFaceColor',blue);
hold on

set(gca,'FontSize', myTextFont); % has no effect on tick label size
set(gca,'Xtick',1:1:4)
set(gca,'XtickLabel',x(1:1:4))
title('Vin and Vout using u-shaped config #3 and PCB v2.1 Redo 4/3');
xlabel('Potentiometer positon adjusts gain (from ~2 to ~6.5)'); % x-axis label
ylabel('Voltage (mV)'); % y-axis label
lgd = legend('Vin 850BP -MBA','Vout 850BP -MBA','Vin 890BP -MBA',...
    'Vout 890BP -MBA','Vin 900BP -MBA','Vout 900BP -MBA',...
    'Vin 850BP +MBA','Vout 850BP +MBA','Vin 890BP +MBA',...
    'Vout 890BP +MBA','Vin 900BP +MBA','Vout 900BP +MBA',...
    'Location','northwest');
title(lgd,'Offset')

function g = saveMyPlot(FigH, myTitle)
global plotOption
    dirStem = "C:\Users\karen\Documents\Data\";
    subDir = "Plots\";
    plotDirStem = sprintf("%s%s", dirStem, subDir);
    switch plotOption
        case {1,2,3}
            myPlotName = sprintf('%s%s', plotDirStem, myTitle);
        case 4
            myPlotName = sprintf('%s%s curve fit', plotDirStem, myTitle);
    end
    saveas(FigH, myPlotName, 'png');
    g = 1;
end